[versions]
# ---------- BUILD ----------
agp = "8.11.2"
hiltCompiler = "1.3.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"

# ---------- ANDROIDX ----------
coreKtx = "1.17.0"
appcompat = "1.7.1"
activity = "1.11.0"
constraintlayout = "2.2.1"
material = "1.13.0"

# ---------- TEST ----------
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# ---------- DI ----------
hilt = "2.52"

# ---------- DATABASE ----------
room = "2.6.1"


[libraries]
# ---------- ANDROIDX ----------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# ---------- TEST ----------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# ---------- HILT ----------
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# ---------- ROOM ----------
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
